#!/usr/bin/env python3
import sys
import requests
from pathlib import Path

def notify(text):
    requests.post("http://127.0.0.1:8899/notify", json={"text": text})

def send_file(filepath):
    path = Path(filepath)
    if not path.is_file():
        print(f"Файл не найден: {filepath}")
        return
    with path.open("rb") as f:
        files = {'file': (path.name, f)}
        requests.post("http://127.0.0.1:8899/send-file", files=files)

if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "notify":
        text = " ".join(sys.argv[2:]).strip('"')
        notify(text)

    elif len(sys.argv) == 3 and sys.argv[1] == "send-file":
        send_file(sys.argv[2])
